### PR TITLE
added Declare an array with more than 5 number of Elements

### PR DESCRIPTION
**Pull request by Shivashish-rwt**
Created an array with 5 number of elements and also an html file to see output in console.

CODE :-

Screenshot (139)

OUTPUT :-

Screenshot (138)

### CODE REVIEW

**Comment by SJ-Kumar** [comment]
@Shivashish-rwt , please move the file to js folder.

**Comment by Shivashish-rwt** [comment]
@SJ-Kumar I have moved the file to js folder.

**Comment by SJ-Kumar** [comment]
@Shivashish-rwt , Can you please verify in https://hacktoberfest.com/ site if it shows the PR accepted status against your github login.

**Comment by Shivashish-rwt** [comment]
I am unable to see accepted tag.

Screenshot (140)

**Comment by SJ-Kumar** [comment]
oh ok...Let us wait for a day and see the changes. I am also not sure how it works.

**Comment by Shivashish-rwt** [comment]
Can u tell me why is it showing excluded tag?

**Comment by SJ-Kumar** [comment]
Looks like they have set of rules to follow for each repository....I am also trying to find those details..

**Pull request merged**
