### PR TITLE
Create declareanarray.js (Issue #1)

### PR DESCRIPTION
**Pull request by AayushBiswas**

### CODE REVIEW

**Comment by SJ-Kumar** [comment]
Thanks for your contribution, Aayush.

**Comment by SJ-Kumar** [comment]
@AayushBiswas , Can you please verify in https://hacktoberfest.com/ site if it shows the PR accepted status against your github login.

**Comment by AayushBiswas** [comment]
No the project shows this repository is excluded

**Comment by SJ-Kumar** [comment]
Let us wait for a day and see if any changes happens..

**Comment by AayushBiswas** [comment]
No changed happen. Repository is excluded from hacktoberfest

**Pull request merged**
